import type { CityConfig } from "@/src/modules/contracts";

export const BENGALURU_CITY_CONFIG: CityConfig = {
  cityId: "bengaluru",
  name: "Bengaluru",
  state: "Karnataka",
  country: "India",
  boundingBox: {
    minLat: 12.7,
    maxLat: 13.3,
    minLng: 77.3,
    maxLng: 77.9,
  },
  addressKeywords: [
    "bengaluru",
    "bangalore",
    "karnataka",
    "kodagalahatti",
    "hunasamaranahalli",
    "yelahanka",
    "mahadevapura",
    "bommanahalli",
  ],
  administrativeHierarchy: {
    corporationName: "Greater Bengaluru Authority (GBA) / BBMP",
    hasZones: true,
    hasWards: true,
    zones: [
      { id: "yelahanka", name: "Yelahanka Zone" },
      { id: "mahadevapura", name: "Mahadevapura Zone" },
      { id: "bommanahalli", name: "Bommanahalli Zone" },
      { id: "east", name: "East Zone" },
      { id: "west", name: "West Zone" },
      { id: "south", name: "South Zone" },
      { id: "dasarahalli", name: "Dasarahalli Zone" },
      { id: "rr_nagar", name: "Rajarajeshwari Nagar Zone" },
    ],
  },
  agencies: [
    {
      agencyId: "bengaluru_bescom",
      cityId: "bengaluru",
      categoryKey: "electricity",
      officialName: "Electricity Distribution (BESCOM)",
      shortCode: "BESCOM",
      contactEmail: "bescom@demo.com",
      emailAliases: ["bescom@demo.com", "electricity@demo.com", "bescom@bengaluru.gov.in"],
      jurisdiction: {
        state: "Karnataka",
        supportedDistricts: [
          "bengaluru urban",
          "bangalore urban",
          "bangalore rural",
          "bengaluru rural",
          "ramanagara",
          "chitradurga",
          "davanagere",
          "kolar",
          "shivamogga",
          "tumakuru",
        ],
        supportedCities: ["bengaluru", "bangalore", "devanahalli", "yelahanka"],
      },
    },
    {
      agencyId: "bengaluru_bwssb",
      cityId: "bengaluru",
      categoryKey: "water",
      officialName: "Water Supply & Sewerage Board (BWSSB)",
      shortCode: "BWSSB",
      contactEmail: "bwssb@demo.com",
      emailAliases: ["bwssb@demo.com", "water@demo.com", "bwssb@bengaluru.gov.in"],
      jurisdiction: {
        state: "Karnataka",
        supportedDistricts: ["bengaluru urban", "bangalore urban", "bbmp"],
        supportedCities: ["bengaluru", "bangalore"],
      },
    },
    {
      agencyId: "bengaluru_bbmp",
      cityId: "bengaluru",
      categoryKey: "sanitation",
      officialName: "Solid Waste & Sanitation (BBMP)",
      shortCode: "BBMP Sanitation",
      contactEmail: "bbmp@demo.com",
      emailAliases: ["bbmp@demo.com", "sanitation@demo.com", "bbmp@bengaluru.gov.in"],
      jurisdiction: {
        state: "Karnataka",
        supportedDistricts: ["bengaluru urban", "bangalore urban", "bbmp", "greater bengaluru authority"],
        supportedCities: ["bengaluru", "bangalore"],
      },
    },
    {
      agencyId: "bengaluru_roads",
      cityId: "bengaluru",
      categoryKey: "roads",
      officialName: "Roads & Highways Division (BBMP Roads)",
      shortCode: "BBMP Roads",
      contactEmail: "roads@demo.com",
      emailAliases: ["roads@demo.com"],
      jurisdiction: {
        state: "Karnataka",
        supportedDistricts: ["bengaluru urban", "bangalore urban", "bbmp"],
        supportedCities: ["bengaluru", "bangalore"],
      },
    },
    {
      agencyId: "bengaluru_traffic",
      cityId: "bengaluru",
      categoryKey: "traffic",
      officialName: "Traffic Management (BTP)",
      shortCode: "BTP Traffic",
      contactEmail: "traffic@demo.com",
      emailAliases: ["traffic@demo.com"],
      jurisdiction: {
        state: "Karnataka",
        supportedDistricts: ["bengaluru urban", "bangalore urban", "bbmp"],
        supportedCities: ["bengaluru", "bangalore"],
      },
    },
    {
      agencyId: "generic_publicworks",
      cityId: "bengaluru",
      categoryKey: "publicworks",
      officialName: "Public Works Department (PWD)",
      shortCode: "PWD",
      contactEmail: "publicworks@demo.com",
      emailAliases: ["publicworks@demo.com", "authority@demo.com"],
      jurisdiction: {
        state: "Karnataka",
        supportedDistricts: ["bengaluru urban", "bangalore urban", "bbmp"],
        supportedCities: ["bengaluru", "bangalore"],
      },
    },
  ],
  version: "1.0.0",
};
