import type { CityConfig } from "@/src/modules/contracts";

export const CHENNAI_CITY_CONFIG: CityConfig = {
  cityId: "chennai",
  name: "Chennai",
  state: "Tamil Nadu",
  country: "India",
  boundingBox: {
    minLat: 12.8,
    maxLat: 13.3,
    minLng: 80.0,
    maxLng: 80.4,
  },
  addressKeywords: [
    "chennai",
    "madras",
    "tamil nadu",
    "cmwssb",
    "ambika street",
    "tangedco",
    "royapuram",
    "adyar",
    "anna nagar",
  ],
  administrativeHierarchy: {
    corporationName: "Greater Chennai Corporation (GCC)",
    hasZones: true,
    hasWards: true,
    zones: [
      { id: "royapuram", name: "Royapuram Zone" },
      { id: "adyar", name: "Adyar Zone" },
      { id: "anna_nagar", name: "Anna Nagar Zone" },
      { id: "t_nagar", name: "T. Nagar Zone" },
    ],
  },
  agencies: [
    {
      agencyId: "chennai_tangedco",
      cityId: "chennai",
      categoryKey: "electricity",
      officialName: "Electricity Distribution (TANGEDCO)",
      shortCode: "TANGEDCO",
      contactEmail: "tangedco@demo.com",
      emailAliases: ["tangedco@demo.com", "tangedco@chennai.gov.in"],
      jurisdiction: {
        state: "Tamil Nadu",
        supportedDistricts: ["chennai", "chennai district", "thiruvallur", "kancheepuram", "chengalpattu"],
        supportedCities: ["chennai"],
      },
    },
    {
      agencyId: "chennai_cmwssb",
      cityId: "chennai",
      categoryKey: "water",
      officialName: "Water Supply & Sewerage Board (CMWSSB)",
      shortCode: "CMWSSB",
      contactEmail: "cmwssb@demo.com",
      emailAliases: ["cmwssb@demo.com"],
      jurisdiction: {
        state: "Tamil Nadu",
        supportedDistricts: ["chennai", "chennai district", "gcc"],
        supportedCities: ["chennai"],
      },
    },
    {
      agencyId: "chennai_gcc",
      cityId: "chennai",
      categoryKey: "sanitation",
      officialName: "Greater Chennai Corporation (GCC Sanitation)",
      shortCode: "GCC",
      contactEmail: "gcc@demo.com",
      emailAliases: ["gcc@demo.com"],
      jurisdiction: {
        state: "Tamil Nadu",
        supportedDistricts: ["chennai", "chennai district", "greater chennai corporation", "gcc"],
        supportedCities: ["chennai"],
      },
    },
    {
      agencyId: "chennai_roads",
      cityId: "chennai",
      categoryKey: "roads",
      officialName: "Chennai Highways & Roads",
      shortCode: "GCC Roads",
      contactEmail: "chennairoads@demo.com",
      emailAliases: ["chennairoads@demo.com"],
      jurisdiction: {
        state: "Tamil Nadu",
        supportedDistricts: ["chennai", "chennai district", "gcc"],
        supportedCities: ["chennai"],
      },
    },
    {
      agencyId: "chennai_traffic",
      cityId: "chennai",
      categoryKey: "traffic",
      officialName: "Chennai Traffic Police",
      shortCode: "CTP",
      contactEmail: "chennaitraffic@demo.com",
      emailAliases: ["chennaitraffic@demo.com"],
      jurisdiction: {
        state: "Tamil Nadu",
        supportedDistricts: ["chennai", "chennai district", "gcc"],
        supportedCities: ["chennai"],
      },
    },
    {
      agencyId: "generic_publicworks",
      cityId: "chennai",
      categoryKey: "publicworks",
      officialName: "Public Works Department (PWD Chennai)",
      shortCode: "PWD Chennai",
      contactEmail: "pwd@chennai.gov.in",
      emailAliases: ["pwdchennai@demo.com"],
    },
  ],
  version: "1.0.0",
};
